name: tformulas
description: "Lista de formulas"
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  shared_preferences: ^2.0.8

flutter:
  uses-material-design: true
